[project]
name = "usgs_m2m"
version = "0.0.1"
description = "Python wrapper of the USGS/EROS Inventory Service Machine-to-Machine API"
authors = [
    {name = "MrChebur", email = "20655102+MrChebur@users.noreply.github.com"},
]
dependencies = [
    "requests",
    "tqdm"
]
